services:
  osrm:
    build:
      context: .
      # Change this value if you use other regions. ex) kansai-latest, kanto-latest..
      # For more information: http://download.geofabrik.de/
      args:
        REGION_VERSION: "tohoku-latest"
    volumes:
      - ./app/src:/app/src
    ports:
      - "5050:5050"
    command: "yarn start"
